const countryCodeMap = {
    'pakistan': 'PAK',
    'pak': 'PAK',
    'india': 'IND',
    'ind': 'IND',
    'united states': 'USA',
    'usa': 'USA',
    'us': 'USA',
    'china': 'CHN',
    'chn': 'CHN',
    'japan': 'JPN',
    'jpn': 'JPN',
    'russia': 'RUS',
    'rus': 'RUS',
    'canada': 'CAN',
    'can': 'CAN',
    'australia': 'AUS',
    'aus': 'AUS',
    'indonesia': 'IDN',
    'idn': 'IDN',
    'brazil': 'BRA',
    'bra': 'BRA',
    'saudi arabia': 'SAU',
    'sau': 'SAU',
    'united arab emirates': 'ARE',
    'uae': 'ARE',
}
